---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjobs
  labels:
    app: cronjobs
    app.kubernetes.io/name: cronjobs
    app.kubernetes.io/part-of: kemo-demos
spec:
  schedule: "*/1 * * * *" # run every minute
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: cronjobs
            app.kubernetes.io/name: cronjobs
            app.kubernetes.io/part-of: kemo-demos
        spec:
          restartPolicy: Never
          containers:
            - name: worker
              image: busybox:1.36
              command: ["sh", "-c"]
              args:
                - |
                  echo "Cron tick from pod ${POD_NAME} on node ${NODE_NAME} at $(date -u +%Y-%m-%dT%H:%M:%SZ)";
              env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
