---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: labels-selectors-v1
  labels:
    app: labels-selectors
    tier: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labels-selectors
      version: v1
  template:
    metadata:
      labels:
        app: labels-selectors
        tier: frontend
        version: v1
    spec:
      volumes:
        - name: web
          emptyDir: {}
      initContainers:
        - name: init-web
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              cat >/work/index.html <<'EOF'
              <!doctype html>
              <html><head><meta charset="utf-8" /><title>Labels & Selectors - v1</title>
              <style>body{font-family:system-ui,sans-serif;padding:20px}</style></head>
              <body>
                <h1>Labels & Selectors Demo</h1>
                <p><strong>Version:</strong> v1</p>
                <p>Labels: app=labels-selectors, tier=frontend, version=v1</p>
                <p>Pod: ${POD_NAME}</p>
                <p>Node: ${NODE_NAME}</p>
              </body></html>
              EOF
          volumeMounts:
            - name: web
              mountPath: /work
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      containers:
        - name: web
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web
              mountPath: /usr/share/nginx/html
