---
resources:
  - backing-secret.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - consumer-deployment.yaml
  - service.yaml
  - ingress.yaml
