---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: eso-store
spec:
  provider:
    kubernetes:
      server: https://kubernetes.default.svc
      auth:
        serviceAccount:
          name: eso-provider
