apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-stable-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - good.canary.demo.local
    secretName: demo-tls
  rules:
  - host: good.canary.demo.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: canary-stable-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-canary-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "30"
spec:
  tls:
  - hosts:
    - good.canary.demo.local
    secretName: demo-tls
  rules:
  - host: good.canary.demo.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: canary-canary-service
            port:
              number: 80