---
apiVersion: batch/v1
kind: Job
metadata:
  name: jobs
  labels:
    app: jobs
    app.kubernetes.io/name: jobs
    app.kubernetes.io/part-of: kemo-demos
spec:
  completions: 3
  parallelism: 2
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: jobs
        app.kubernetes.io/name: jobs
        app.kubernetes.io/part-of: kemo-demos
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              echo "Starting job task in pod ${POD_NAME} on node ${NODE_NAME}";
              sleep 2;
              echo "Job task complete in pod ${POD_NAME}";
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
