---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volumes-web
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Kubernetes Volumes Demo</title>
        <style>body{font-family:system-ui,sans-serif;padding:20px;line-height:1.5}</style>
        <script>
          async function poll() {
            try {
              const r = await fetch('runtime/heartbeat.txt', { cache: 'no-store' });
              const txt = await r.text();
              document.getElementById('hb').textContent = txt.trim();
            } catch (e) {
              document.getElementById('hb').textContent = 'unavailable';
            }
            setTimeout(poll, 3000);
          }
          window.onload = poll;
        </script>
      </head>
      <body>
        <h1>Volumes: ConfigMap + emptyDir</h1>
        <p>This page (index.html) is served from a ConfigMap volume.</p>
        <p>Heartbeat below is written by a sidecar to an emptyDir volume and served at <code>/runtime/heartbeat.txt</code>.</p>
        <pre id="hb">starting…</pre>
      </body>
    </html>
