---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-defaults
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "50m"
        memory: "32Mi"
      default:
        cpu: "100m"
        memory: "64Mi"
      min:
        cpu: "25m"
        memory: "16Mi"
      max:
        cpu: "200m"
        memory: "128Mi"
