---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-compute-and-objects
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "128Mi"
    limits.cpu: "400m"
    limits.memory: "256Mi"
    pods: "5"
    services: "5"
    configmaps: "10"
