---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-disruption-budget
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-disruption-budget
  template:
    metadata:
      labels:
        app: pod-disruption-budget
    spec:
      terminationGracePeriodSeconds: 20
      volumes:
        - name: web
          emptyDir: {}
      initContainers:
        - name: init-web
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              cat >/work/index.html <<'EOF'
              <!doctype html>
              <html>
                <head>
                  <meta charset="utf-8" />
                  <title>Pod Disruption Budget (PDB)</title>
                  <style>body{font-family:system-ui,sans-serif;padding:20px}</style>
                </head>
                <body>
                  <h1>Pod Disruption Budget Demo</h1>
                  <p>This app runs 3 replicas behind a Service. A PDB limits voluntary disruptions.</p>
                  <ul>
                    <li>Deployment replicas: 3</li>
                    <li>PDB: minAvailable: 2</li>
                  </ul>
                  <p>Pod: ${POD_NAME}</p>
                  <p>Node: ${NODE_NAME}</p>
                </body>
              </html>
              EOF
          volumeMounts:
            - name: web
              mountPath: /work
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      containers:
        - name: web
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web
              mountPath: /usr/share/nginx/html
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
