---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qos-guaranteed
  labels:
    app: qos-guaranteed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qos-guaranteed
  template:
    metadata:
      labels:
        app: qos-guaranteed
    spec:
      volumes:
        - name: web
          emptyDir: {}
      initContainers:
        - name: init-web
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              cat >/work/index.html <<'EOF'
              <!doctype html>
              <html><head><meta charset="utf-8" /><title>QoS: Guaranteed</title>
              <style>body{font-family:system-ui,sans-serif;padding:20px}</style></head>
              <body>
                <h1>QoS Class: Guaranteed</h1>
                <p>Requests equal limits for all containers and resources (cpu, memory).</p>
                <pre>requests == limits:
                cpu: 100m
                memory: 64Mi</pre>
                <p>Pod: ${POD_NAME}</p>
                <p>Node: ${NODE_NAME}</p>
              </body></html>
              EOF
          volumeMounts:
            - name: web
              mountPath: /work
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      containers:
        - name: web
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
