---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qos-burstable
  labels:
    app: qos-burstable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qos-burstable
  template:
    metadata:
      labels:
        app: qos-burstable
    spec:
      volumes:
        - name: web
          emptyDir: {}
      initContainers:
        - name: init-web
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              cat >/work/index.html <<'EOF'
              <!doctype html>
              <html><head><meta charset="utf-8" /><title>QoS: Burstable</title>
              <style>body{font-family:system-ui,sans-serif;padding:20px}</style></head>
              <body>
                <h1>QoS Class: Burstable</h1>
                <p>Requests are set lower than limits, allowing bursts above the requested baseline.</p>
                <pre>requests:
                cpu: 50m
                memory: 32Mi
              limits:
                cpu: 200m
                memory: 64Mi</pre>
                <p>Pod: ${POD_NAME}</p>
                <p>Node: ${NODE_NAME}</p>
              </body></html>
              EOF
          volumeMounts:
            - name: web
              mountPath: /work
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      containers:
        - name: web
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
